

    
    public static void main(String[] args) {
       package br.ulbra.view;

import java.util.Calendar;
import javax.swing.JOptionPane;
import static javax.swing.LayoutStyle.getInstance;

/**
 *
 * @author s.lucas
 */
public class FolhaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form FolhaPagamento
     */
    public FolhaPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbFolha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbHolaroideFixo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbFuncionarioFixo = new javax.swing.JLabel();
        lbQHorasFixo = new javax.swing.JLabel();
        lbSalarioBrutoFixo = new javax.swing.JLabel();
        lbINSSFixo = new javax.swing.JLabel();
        lbIRFixo = new javax.swing.JLabel();
        lbQHExtrasFixo = new javax.swing.JLabel();
        lbHoraExtraFixo = new javax.swing.JLabel();
        lbSalFamiFixo = new javax.swing.JLabel();
        lbSalarioFixo = new javax.swing.JLabel();
        lbFuncionarioR = new javax.swing.JLabel();
        lbQHorasR = new javax.swing.JLabel();
        lbSalBrutR = new javax.swing.JLabel();
        lbINSS = new javax.swing.JLabel();
        lbIR = new javax.swing.JLabel();
        lbHolaroide = new javax.swing.JLabel();
        lbQHExtrasR = new javax.swing.JLabel();
        lbVHExtraR = new javax.swing.JLabel();
        lbVSFamiliaR = new javax.swing.JLabel();
        lbSalario = new javax.swing.JLabel();
        lbFuncionario = new javax.swing.JLabel();
        txtFuncionario = new javax.swing.JTextField();
        lbQHoras = new javax.swing.JLabel();
        txtQHora = new javax.swing.JTextField();
        lbValorH = new javax.swing.JLabel();
        txtVHora = new javax.swing.JTextField();
        lbQFilhos = new javax.swing.JLabel();
        txtQFilhos = new javax.swing.JTextField();
        lbQHExtras = new javax.swing.JLabel();
        txtQHExtras = new javax.swing.JTextField();
        btnGerar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbFolha.setText("FOLHA DE PAGAMENTO");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        lbHolaroideFixo.setText("HOLERITE -");

        lbFuncionarioFixo.setText("FUNCIONÁRIO:");

        lbQHorasFixo.setText("QUANT. HORAS:");

        lbSalarioBrutoFixo.setText("SALÁRIO BRUTO: R$");

        lbINSSFixo.setText("DESCONTO INSS: R$");

        lbIRFixo.setText("DESCONTO IR: R$");

        lbQHExtrasFixo.setText("QUANT. HORAS EXTRAS:");

        lbHoraExtraFixo.setText("VALOR HORAS EXTRA : R$");

        lbSalFamiFixo.setText("VAL. SAL. FAMILIA: R$");

        lbSalarioFixo.setText("SALARIO LIQUIDO");

        lbFuncionarioR.setText("???");

        lbQHorasR.setText("???");

        lbSalBrutR.setText("???");

        lbINSS.setText("???");

        lbIR.setText("???");

        lbHolaroide.setText("???");

        lbQHExtrasR.setText("???");

        lbVHExtraR.setText("???");

        lbVSFamiliaR.setText("???");

        lbSalario.setText("???");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbQHorasFixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbQHorasR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbSalarioBrutoFixo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lbSalBrutR)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbHoraExtraFixo)
                        .addGap(18, 18, 18)
                        .addComponent(lbVHExtraR, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbSalFamiFixo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbVSFamiliaR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbIRFixo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbIR))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbINSSFixo)
                                .addGap(18, 18, 18)
                                .addComponent(lbINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(lbSalarioFixo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbFuncionarioFixo)
                                .addGap(18, 18, 18)
                                .addComponent(lbFuncionarioR, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbHolaroideFixo)
                                .addGap(30, 30, 30)
                                .addComponent(lbHolaroide, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbQHExtrasFixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbQHExtrasR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHolaroide)
                    .addComponent(lbHolaroideFixo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFuncionarioFixo)
                    .addComponent(lbFuncionarioR))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQHExtrasFixo)
                            .addComponent(lbQHExtrasR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQHorasFixo)
                            .addComponent(lbQHorasR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbSalFamiFixo)
                                .addComponent(lbVSFamiliaR))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbSalarioBrutoFixo)
                                .addComponent(lbSalBrutR)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHoraExtraFixo)
                            .addComponent(lbVHExtraR))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbINSSFixo)
                            .addComponent(lbINSS)
                            .addComponent(lbSalarioFixo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbIRFixo)
                            .addComponent(lbIR)
                            .addComponent(lbSalario))
                        .addGap(16, 16, 16))))
        );

        lbFuncionario.setText("FUNCIOÁRIO");

        lbQHoras.setText("QUANT. HORA");

        lbValorH.setText("VALOR DA HORA");

        lbQFilhos.setText("QUANT. FILHOS");

        lbQHExtras.setText("QUANT.HORAS EXTRAS");

        btnGerar.setText("GERAR FOLHA");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lbFolha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbFuncionario)
                                .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbQHoras)
                                    .addComponent(lbQFilhos)
                                    .addComponent(txtQHora, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGerar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbQHExtras)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtVHora)
                                                .addComponent(lbValorH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(txtQHExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLimpar)
                                        .addGap(20, 20, 20)))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFolha)
                .addGap(33, 33, 33)
                .addComponent(lbFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQHoras)
                    .addComponent(lbValorH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQFilhos)
                    .addComponent(lbQHExtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQHExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerar)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {                                          
        txtFuncionario.setText(null);
        txtQHora.setText(null);
        txtVHora.setText(null);
        txtQFilhos.setText(null);
        txtQHExtras.setText(null);
        lbHolaroide.setText("???");
        lbFuncionarioR.setText("???");
        lbQHExtrasR.setText("???");
        lbQHorasR.setText("???");
        lbSalBrutR.setText("???");
        lbINSS.setText("???");
        lbIR.setText("???");
        lbVHExtraR.setText("???");
        lbVSFamiliaR.setText("???");
        lbSalario.setText("???");
        lbHolaroide.setText("???");
        JOptionPane.showMessageDialog(null, "campo limpo com sucesso!");
    }                                        

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String nome;

        double qHoras,salHExtra, qHorasExtra, vHora, sBruto, iNSS, iR, sLiquido, filhos, sFamilia;
        Calendar hoje = Calendar.getInstance();
        int mes = hoje.get(Calendar.MONTH) + 1;
        int ano = hoje.get(Calendar.YEAR);
                nome = txtFuncionario.getText();
        qHoras = Double.parseDouble(txtQHora.getText());
        vHora = Double.parseDouble(txtVHora.getText());
        filhos = Double.parseDouble(txtQFilhos.getText());
        qHorasExtra = Double.parseDouble(txtQHExtras.getText());
        sBruto = qHoras*vHora;
        salHExtra = qHorasExtra*vHora*1.5;
        sFamilia = filhos*15;
        if(sBruto<=1320){
            iNSS= sBruto*0.075;
        }else if (sBruto>1320&&sBruto<=2571.29){
            iNSS= sBruto*0.09;
        }else if (sBruto>2571.29&&sBruto<=3856.94){
            iNSS= sBruto*0.12;
        }else {
            iNSS= sBruto*0.14;
        }
        if(sBruto<=1903.09){
            iR=0;
        }else if (sBruto>1903.09&&sBruto<=2826.65){
            iR=sBruto*0.075;
        }else if (sBruto>2826.65&&sBruto<=3751.05){
            iR=sBruto*0.15;
        }else if (sBruto>3751.05&&sBruto<=4664.68){
            iR=sBruto*0.225;
        }else {
            iR=sBruto*0.275;
        }
        sLiquido = sBruto+salHExtra+sFamilia-iNSS-iR;
        lbFuncionarioR.setText(nome);
        lbQHExtrasR.setText(String.valueOf(qHorasExtra));
        lbQHorasR.setText(String.valueOf(qHoras));
        lbSalBrutR.setText(String.valueOf("R$"+sBruto));
        lbINSS.setText(String.valueOf("R$"+iNSS));
        lbIR.setText(String.valueOf("R$"+iR));
        lbVHExtraR.setText(String.valueOf("R$"+salHExtra));
        lbVSFamiliaR.setText(String.valueOf("R$"+sFamilia));
        lbSalario.setText(String.valueOf("R$"+sLiquido));
        lbHolaroide.setText(mes + "/" + ano);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FolhaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FolhaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FolhaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FolhaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FolhaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                    
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFolha;
    private javax.swing.JLabel lbFuncionario;
    private javax.swing.JLabel lbFuncionarioFixo;
    private javax.swing.JLabel lbFuncionarioR;
    private javax.swing.JLabel lbHolaroide;
    private javax.swing.JLabel lbHolaroideFixo;
    private javax.swing.JLabel lbHoraExtraFixo;
    private javax.swing.JLabel lbINSS;
    private javax.swing.JLabel lbINSSFixo;
    private javax.swing.JLabel lbIR;
    private javax.swing.JLabel lbIRFixo;
    private javax.swing.JLabel lbQFilhos;
    private javax.swing.JLabel lbQHExtras;
    private javax.swing.JLabel lbQHExtrasFixo;
    private javax.swing.JLabel lbQHExtrasR;
    private javax.swing.JLabel lbQHoras;
    private javax.swing.JLabel lbQHorasFixo;
    private javax.swing.JLabel lbQHorasR;
    private javax.swing.JLabel lbSalBrutR;
    private javax.swing.JLabel lbSalFamiFixo;
    private javax.swing.JLabel lbSalario;
    private javax.swing.JLabel lbSalarioBrutoFixo;
    private javax.swing.JLabel lbSalarioFixo;
    private javax.swing.JLabel lbVHExtraR;
    private javax.swing.JLabel lbVSFamiliaR;
    private javax.swing.JLabel lbValorH;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextField txtQFilhos;
    private javax.swing.JTextField txtQHExtras;
    private javax.swing.JTextField txtQHora;
    private javax.swing.JTextField txtVHora;
    // End of variables declaration                  
}
